### ISSUE TITLE
to execute the mongodb query with javascript function

### ISSUE THREAD

**Issue by rajsekarm1** [coldze/mongol#8]
**Describe the bug**
Need to execute the following query which are executed properly in mongodb command line. 
But facing issue while placing and executing from Mongol framework file. 

Here is the script details:

db.runCommand(
{
  "aggregate": "me_me",
}).result.forEach(
function(e,i) {
    var existingvalue = e.ctr.opstatus.ovalstts;
    var newValue = (existingvalue === "uknwnall") ?  "not started" : "started"; 
    e.ctr.cldepsts1 = e.ctr.cldepsts1.replace('##ctr.opstatus.ovalstts##', newValue);
    db.me_me.save(e);
})

**Comment by coldze** [comment]
Hi @rajsekarm1 ,

What you're actually doing in this querry is you're aggregating data and applying JavaScript function to each item in result. You can do this by placing the whole code you've mentioned in JavaScript function and calling it in migration with `eval` command.
It won't be convenient to read, as JSON doesn't support multiline strings.
In addition, MongoDB starting from v4.0 deprecates JavaScript, so try to avoid such manipulations and use standard MongoDB operators instead.

Migration example with JavaScript inside:
```
{
    "eval": "function(nameArg) {db.test_js.insert({name: nameArg});}",
    "args": ["test-name"]
}
```

I'll probably think of supporting an ability to include JavaScript functions as files in migrations (adding preprocessing step that will substitute content), in this case it will be at least easier to read them.
