### ISSUE TITLE
Invoking function works in db.runCommand where it fails in the while invoking via mongol tool. 

### ISSUE THREAD

**Issue by rajsekarm1** [coldze/mongol#9]
Below is my run command and works fine perfectly. 
db.runCommand( {
   "aggregate": "inventory2",
   "pipeline": [
      { "$addFields":{"name": { "$concat": [ "$item", convertIndiviualState("$item"), "$item" ] }}},
      { "$out": "inventory2" }
   ],
   "cursor": { }
   }) 

But the same one I am placing it in json file and invoking via mongol facing the issue. 

{
  "cmds": [
		{
			"aggregate": "inventory2",
			"pipeline": [
				{ "$addFields":{"name": { "$concat": [ "$item", convertIndiviualState("$item"), "$item" ] }}},
				{ "$out": "inventory2" }
			],
			"cursor": { }
		}
	]
}

Below is the error:

 Error: Failed to generate migration from file 'deployment.json'. Error: C:/Users/rajasekarm/go/src/github.com/coldze/mongol/engine/decoding/ext_json.go:23
        Error: Failed to decode ext-json. Error: invalid JSON input. Position: 122. Character: c

The script  complains for the invocation of function.

**Comment by coldze** [comment]
Hi @rajsekarm1,

Sure it will fail. You've inserted `convertIndiviualState`. Have no idea what's that, but in any case, it brakes JSON format. It must be in quotes.

**Comment by rajsekarm1** [comment]
Hi Norman,

convertIndiviualState Is the function created and stored. 
I have tried different combinations by using comma, eventually it failed while invoking the function. Please provide the snippet to invoke a function in the Jason format to fit into framework. 

Regards,
Rajasekar M

**Comment by coldze** [comment]
Hi @rajsekarm1,

I don't think, that putting invokation of stored js to ExtJSON and then applying through mongo-driver will work.
The only possible solution in this case, that comes to my mind, is putting the whole code inside JavaScript function (aggregation, pipeline, everything) and going with `eval` command.
